"""
Django settings for football_site project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.conf.global_settings import STATICFILES_DIRS


# ===== Projekti baaskataloog =====
# BASE_DIR viitab projekti juurkaustale
BASE_DIR = Path(__file__).resolve().parent.parent


# ===== Arendusseaded =====
# NB! Need seaded EI sobi tootmiskeskkonda

# Turvavõti (SECRET_KEY)
# Kasutatakse krüpteerimiseks ja sessioonide turvamiseks
SECRET_KEY = 'django-insecure-%+7v(&o*d6p&x3vo1n%))0x!p_ui(%uhwga9xx0xqk$rb=@n9u'

# DEBUG = True tähendab, et veateated kuvatakse detailselt
# Tootmises peab see olema False
DEBUG = True

# Lubatud hostid (tühi arenduse ajal)
ALLOWED_HOSTS = []


# ===== Rakenduste definitsioon =====
INSTALLED_APPS = [
    # Django sisseehitatud rakendused
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Projekti enda rakendused
    'clubs',
    'main',
]


# ===== Middleware (vahekihtide) seadistus =====
# Middleware töötleb HTTP päringuid enne ja pärast view'd
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ===== URL-ide põhikonfiguratsioon =====
ROOT_URLCONF = 'football_site.urls'


# ===== Mallide (templates) seadistus =====
TEMPLATES = [
    {
        # Django mallimootor
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # Globaalne templates kaust
        'DIRS': [BASE_DIR / 'templates'],

        # Otsib template faile ka rakenduste sees
        'APP_DIRS': True,

        # Kontekstiprotsessorid (lisavad andmeid mallidesse)
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ===== WSGI rakendus =====
# Kasutatakse tootmiskeskkonnas serveriga suhtlemiseks
WSGI_APPLICATION = 'football_site.wsgi.application'


# ===== Andmebaasi seadistus =====
# Kasutatakse SQLite andmebaasi (sobib arenduseks)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ===== Parooli valideerimine =====
# Tagab kasutajate paroolide turvalisuse
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ===== Rahvusvahelistamine =====
# Keele- ja ajavööndi seaded
LANGUAGE_CODE = 'en-us'   # Lehe vaikekeel

TIME_ZONE = 'UTC'         # Ajavöönd

USE_I18N = True           # Rahvusvahelistamise lubamine
USE_TZ = True             # Ajavööndite kasutamine


# ===== Staatilised failid =====
# CSS, JavaScript ja pildid
STATIC_URL = 'static/'

# Staatiliste failide kaust
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]


# ===== Vaikimisi primaarvõtme tüüp =====
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

